# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Elements_info_template.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 561))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ar_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ar_label.sizePolicy().hasHeightForWidth())
        self.ar_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ar_label.setFont(font)
        self.ar_label.setObjectName("ar_label")
        self.gridLayout.addWidget(self.ar_label, 1, 0, 1, 1)
        self.interesting_facts_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.interesting_facts_label.setFont(font)
        self.interesting_facts_label.setStyleSheet("#interesting_facts_label{\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-color: black;\n"
"}")
        self.interesting_facts_label.setAlignment(QtCore.Qt.AlignCenter)
        self.interesting_facts_label.setObjectName("interesting_facts_label")
        self.gridLayout.addWidget(self.interesting_facts_label, 6, 0, 1, 3)
        self.electronegativity_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.electronegativity_label.sizePolicy().hasHeightForWidth())
        self.electronegativity_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.electronegativity_label.setFont(font)
        self.electronegativity_label.setObjectName("electronegativity_label")
        self.gridLayout.addWidget(self.electronegativity_label, 2, 0, 1, 1)
        self.config_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_label.sizePolicy().hasHeightForWidth())
        self.config_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.config_label.setFont(font)
        self.config_label.setObjectName("config_label")
        self.gridLayout.addWidget(self.config_label, 3, 0, 1, 1)
        self.type_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_label.sizePolicy().hasHeightForWidth())
        self.type_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.type_label.setFont(font)
        self.type_label.setObjectName("type_label")
        self.gridLayout.addWidget(self.type_label, 4, 0, 1, 1)
        self.ox_states_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ox_states_label.sizePolicy().hasHeightForWidth())
        self.ox_states_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.ox_states_label.setFont(font)
        self.ox_states_label.setObjectName("ox_states_label")
        self.gridLayout.addWidget(self.ox_states_label, 5, 0, 1, 1)
        self.picture = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.picture.setFont(font)
        self.picture.setStyleSheet("#picture{\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-color: black;\n"
"}")
        self.picture.setText("")
        self.picture.setScaledContents(True)
        self.picture.setAlignment(QtCore.Qt.AlignCenter)
        self.picture.setObjectName("picture")
        self.gridLayout.addWidget(self.picture, 0, 2, 4, 1)
        self.name_label = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 0, 0, 1, 1)
        self.name_data_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name_data_label.setFont(font)
        self.name_data_label.setStyleSheet("#name_data_label{\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-color: black;\n"
"}")
        self.name_data_label.setText("")
        self.name_data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_data_label.setObjectName("name_data_label")
        self.gridLayout.addWidget(self.name_data_label, 0, 1, 1, 1)
        self.ar_data_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ar_data_label.setFont(font)
        self.ar_data_label.setStyleSheet("#ar_data_label{\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-color: black;\n"
"}")
        self.ar_data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ar_data_label.setObjectName("ar_data_label")
        self.gridLayout.addWidget(self.ar_data_label, 1, 1, 1, 1)
        self.electronegativity_data_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.electronegativity_data_label.setFont(font)
        self.electronegativity_data_label.setStyleSheet("#electronegativity_data_label{\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-color: black;\n"
"}")
        self.electronegativity_data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.electronegativity_data_label.setObjectName("electronegativity_data_label")
        self.gridLayout.addWidget(self.electronegativity_data_label, 2, 1, 1, 1)
        self.config_data_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.config_data_label.setFont(font)
        self.config_data_label.setStyleSheet("#config_data_label{\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-color: black;\n"
"}")
        self.config_data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.config_data_label.setObjectName("config_data_label")
        self.gridLayout.addWidget(self.config_data_label, 3, 1, 1, 1)
        self.type_data_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.type_data_label.setFont(font)
        self.type_data_label.setStyleSheet("#type_data_label{\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-color: black;\n"
"}")
        self.type_data_label.setAlignment(QtCore.Qt.AlignCenter)
        self.type_data_label.setObjectName("type_data_label")
        self.gridLayout.addWidget(self.type_data_label, 4, 1, 1, 1)
        self.ox_states_data = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ox_states_data.setFont(font)
        self.ox_states_data.setStyleSheet("#ox_states_data{\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-color: black;\n"
"}")
        self.ox_states_data.setAlignment(QtCore.Qt.AlignCenter)
        self.ox_states_data.setObjectName("ox_states_data")
        self.gridLayout.addWidget(self.ox_states_data, 5, 1, 1, 2)
        self.quote_label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.quote_label.setFont(font)
        self.quote_label.setStyleSheet("#quote_label{\n"
"    border-style: solid;\n"
"    border-width: 5px;\n"
"    border-color: color;\n"
"}")
        self.quote_label.setText("")
        self.quote_label.setScaledContents(False)
        self.quote_label.setAlignment(QtCore.Qt.AlignCenter)
        self.quote_label.setWordWrap(False)
        self.quote_label.setOpenExternalLinks(True)
        self.quote_label.setObjectName("quote_label")
        self.gridLayout.addWidget(self.quote_label, 4, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ar_label.setText(_translate("Form", "Relative\n"
"atomic mass"))
        self.electronegativity_label.setText(_translate("Form", "Electronegativity\n"
"(Pauling)"))
        self.config_label.setText(_translate("Form", "Electonic\n"
"configuration"))
        self.type_label.setText(_translate("Form", "Type"))
        self.ox_states_label.setText(_translate("Form", "Possible\n"
"oxidation states"))
        self.name_label.setText(_translate("Form", "Name"))
